#!/bin/bash
set -e # To stop as soon as an error occured

IDIR="/root/simplescalar/build"

# Build f2c tool
yes | cp -rf $IDIR/../f2c-addition/* $IDIR/f2c-1994.09.27
cd $IDIR/f2c-1994.09.27
make all
make install
