#!/bin/bash

# Make bashline configurations.
set -e
RESET='\033[0m'
COLOR='\033[1;32m'

function msg {
  echo -e "${COLOR}$(date): $1${RESET}"
}

function fail {
  msg "Error : $?"
  exit 1
}

function mcd {
  mkdir -p "$1" || fail
  cd "$1" || fail
}

# The script for installing newest ffmpeg
apt-get -y update -qq || fail && apt-get -y install git || fail

apt-get -y update || fail && apt-get -y upgrade || fail && apt-get -y dist-upgrade || fail && apt-get -y autoremove || fail && apt-get -y autoclean || fail

SOURCE_PATH="/apps/source/"
BUILD_PATH="/usr/local/bin"
mkdir -p $SOURCE_PATH || fail

# Install noVNC
msg "Install noVNC."
cd $SOURCE_PATH || fail
git clone https://github.com/novnc/noVNC.git || fail
ln -s $SOURCE_PATH/noVNC/utils/launch.sh $BUILD_PATH/noVNC

msg "Installation finished."