#!/bin/bash

# Make bashline configurations.
set -e
RESET='\033[0m'
COLOR='\033[1;32m'

function msg {
  echo -e "${COLOR}$(date): $1${RESET}"
}

function fail {
  msg "Error : $?"
  exit 1
}

function mcd {
  mkdir -p "$1" || fail
  cd "$1" || fail
}

# The script for installing newest ffmpeg
apt-get -y update -qq || fail && apt-get -y install \
  autoconf \
  automake \
  build-essential \
  cmake \
  git-core \
  pkg-config \
  wget \
  zlib1g-dev \
  build-essential \
  software-properties-common \
  python-software-properties \
  python3-software-properties || fail

apt-get -y update || fail && apt-get -y upgrade || fail && apt-get -y dist-upgrade || fail && apt-get -y autoremove || fail && apt-get -y autoclean || fail

SOURCE_PATH="/apps/source/gcc"
BUILD_PATH="/apps/build/gcc"
BIN_PATH="/usr/local"
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
MKL_CBWR=AUTO
mkdir -p $SOURCE_PATH $BUILD_PATH $BIN_PATH/gcc-6 $BIN_PATH/gcc-8 || fail



# Install libprotobuf with gcc-5
apt-get install -y libprotobuf-dev python-protobuf || fail
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90 --slave /usr/bin/g++ g++ /usr/bin/g++-5 || fail
SOURCE_PATH="/apps/source"
BUILD_PATH="/apps/build"
BIN_PATH="/usr/local"
# Build and install protobuf
cd $SOURCE_ROOT_PATH || fail
git clone -b 'v3.5.1' --single-branch --depth 1 https://github.com/google/protobuf.git || fail
cd protobuf || fail
./autogen.sh || fail
cd $BUILD_PATH || fail
mkdir -p protobuf || fail && cd protobuf || fail
$SOURCE_ROOT_PATH/protobuf/configure           \
    --prefix=$BIN_PATH || fail
make -j32 || fail
make -j32 install || fail
ldconfig || fail
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 --slave /usr/bin/g++ g++ /usr/bin/g++-5 || fail

echo "export LD_LIBRARY_PATH=$BIN_PATH/lib64:\$LD_LIBRARY_PATH" >> ~/.bashrc 
export LD_LIBRARY_PATH=$BIN_PATH/lib64:$LD_LIBRARY_PATH

msg "Installation finished. Now you could use \"update-alternatives --config gcc\" to control the version of gcc/g++."
msg "Installation finished. Now you could use \"update-alternatives --config gfortran\" to control the version of gfortran."
