#!/bin/bash

# Make bashline configurations.
set -e
RESET='\033[0m'
COLOR='\033[1;32m'

function msg {
  echo -e "${COLOR}$(date): $1${RESET}"
}

function fail {
  msg "Error : $?"
  exit 1
}

function mcd {
  mkdir -p "$1" || fail
  cd "$1" || fail
}

# The script for protobuf-3.5.1 and libbootstrap-1.66
apt-get -y update -qq || fail && apt-get -y install \
  autoconf \
  automake \
  build-essential \
  cmake \
  git-core \
  pkg-config \
  wget \
  zlib1g-dev \
  build-essential \
  software-properties-common \
  python-software-properties \
  python3-software-properties || fail

apt-get -y update || fail && apt-get -y upgrade || fail && apt-get -y dist-upgrade || fail && apt-get -y autoremove || fail && apt-get -y autoclean || fail

SOURCE_ROOT_PATH="/apps/source"
BUILD_PATH="/apps/build"
BIN_PATH="/usr/local"
mkdir -p $SOURCE_ROOT_PATH $BUILD_PATH $BIN_PATH || fail

# Build and install protobuf
cd $SOURCE_ROOT_PATH || fail
git clone -b 'v3.5.1' --single-branch --depth 1 https://github.com/google/protobuf.git || fail
cd protobuf || fail
./autogen.sh || fail
cd $BUILD_PATH || fail
mkdir -p protobuf || fail && cd protobuf || fail
$SOURCE_ROOT_PATH/protobuf/configure           \
    --prefix=$BIN_PATH || fail
make -j32 || fail
make -j32 install || fail
ldconfig || fail