#!/bin/bash

PORT=0
IP=192.168.127.128:5901

for ARGUMENT in "$@"
do
    KEY=$(echo $ARGUMENT | cut -f1 -d=)
    VALUE=$(echo $ARGUMENT | cut -f2 -d=)   
    case "$KEY" in
            PORT)  PORT=${VALUE} ;;
            IP)    IP=${VALUE} ;;     
            *)   
    esac    
done

MACHINE_IP=$(hostname -I | awk 'NR==1 {print $1}')

echo "****************************"
echo "* noVNC Shortcut by Yuchen *"
echo "****************************"

if [ "$PORT" = "0" ]
then
    SHOWPORT=6080
    echo "Default listening port = 6080"
else
    SHOWPORT=$PORT
fi

echo "Current container IP = $IP"

echo "---------------------"
echo "Note that you need to replace \"$HOSTNAME\" with \"$MACHINE_IP\" in the URL"
echo "    http://$MACHINE_IP:$SHOWPORT/vnc.html?host=$MACHINE_IP&port=$SHOWPORT"
echo "---------------------"

if [ "$PORT" = "0" ]
then
    /usr/local/bin/noVNCbin/utils/launch.sh --vnc $IP
else
    /usr/local/bin/noVNCbin/utils/launch.sh --vnc $IP --listen $PORT
fi
