#!/bin/bash

LIBRARY_PATH="/usr/local/cuda/lib64/stubs:"
LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/lib:/usr/lib:/usr/local/lib"
export LD_LIBRARY_PATH
export LIBRARY_PATH

export MKL_CBWR=AUTO
alias python=python3
alias pip=pip3

export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig
export PKG_CONFIG_LIBDIR=/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu:/usr/local/lib
