#!/bin/sh

nvm_has(){
    type "$1" > /dev/null 2>&1
}

# Uncomment the following two lines for normal desktop:
sudo /etc/init.d/dbus restart
# if nvm_has "dbus-launch"; then
#   unset SESSION_MANAGER
#   unset DBUS_SESSION_BUS_ADDRESS
#   dbus-launch xfce4-session
# fi

OS=`uname -s`
if [ $OS = 'Linux' ]; then
  case "$WINDOWMANAGER" in
    *gnome*)
      if [ -e /etc/SuSE-release ]; then
        PATH=$PATH:/opt/gnome/bin
        export PATH
      fi
      ;;
  esac
fi
#[ -x /etc/X11/xinit/xinitrc ] && exec /etc/X11/xinit/xinitrc
#[ -f /etc/X11/xinit/xinitrc ] && exec sh /etc/X11/xinit/xinitrc
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
[ -s /etc/init.d/dbus ] && /etc/init.d/dbus start
#vncconfig -iconic &
xsetroot -solid grey
#xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &

startxfce4 &
