#!/bin/sh

# The following scripts are used for fixing these issues:
# 1. The required library of the libreoffice should be loaded correctly.
# 2. xhost should enable the user to launch a GUI window by root (sudo).
# 3. The options should be passed to the default xinitrc script of
#    Xfce4 correctly.

LD_LIBRARY_PATH="/usr/lib/libreoffice/program:$LD_LIBRARY_PATH"

xhost +SI:localuser:root

exec sh /etc/xdg/xfce4/xinitrc $@
