#!/bin/bash

# Make bashline configurations.
set -e
RESET='\033[0m'
COLOR='\033[1;32m'

function msg {
    echo -e "${COLOR}$(date): $1${RESET}"
}

function fail {
    msg "Error : $?"
    exit 1
}

function mcd {
    mkdir -p "$1" || fail
    cd "$1" || fail
}

MODE=python
JLAB_VERSION=unset
JLAB_EXTRA_TIERS=2
JLAB_COMPATIBLE=false

for ARGUMENT in "$@"
do
    KEY=$(echo $ARGUMENT | cut -f1 -d=)
    VALUE=$(echo $ARGUMENT | cut -f2 -d=)   
    case "$KEY" in
        MODE)               MODE=${VALUE} ;;
        JLAB_VER)           JLAB_VERSION=${VALUE} ;;
        JLAB_EXTIERS)       JLAB_EXTRA_TIERS=${VALUE} ;;
        JLAB_COMPAT)        JLAB_COMPATIBLE=${VALUE} ;;
        *)   
    esac    
done

if [ "x${MODE}" = "xpython" ]
then
    apt-get -y install lsb-release lsb-core || fail
    UBUNTU_VER=$(echo $(lsb_release -a | head -n 4 | tail -1 | awk '{ print $2 }'))

    apt-get install -y --no-install-recommends apt-transport-https || fail
    apt-get install -y at-spi2-core || fail
    apt-get update -y || fail && apt-get -y dist-upgrade || fail
    
    if [ "x${JLAB_COMPATIBLE}" = "xtrue" ]
    then
        curl https://github.com/cainmagi/Dockerfiles/releases/download/jlab-v1.1/get-pip-20.3.4.py -o /root/get-pip-3.py || fail
    else
        curl https://bootstrap.pypa.io/get-pip.py -o /root/get-pip-3.py || fail
    fi
    curl https://bootstrap.pypa.io/2.7/get-pip.py -o /root/get-pip-2.py || fail
    if [ "x${UBUNTU_VER}" = "x20.04" ] || [ "x${UBUNTU_VER}" = "x18.04" ]
    then
        apt-get install -y python3-pip || fail
        python3 /root/get-pip-3.py --force-reinstall || fail
        python3 -m pip install matplotlib plotly Cython numpy scipy scikit-learn scikit-image ipython h5py leveldb networkx nose pandas python-dateutil protobuf python-gflags pyyaml Pillow six Jinja2 Flask || fail
    else
        apt-get install -y python-pip python3-pip || fail
        python3 /root/get-pip-3.py --force-reinstall || fail && python2 /root/get-pip-2.py --force-reinstall || fail
        python3 -m pip install matplotlib plotly Cython numpy scipy scikit-learn scikit-image ipython h5py leveldb networkx nose pandas python-dateutil protobuf python-gflags pyyaml Pillow six Jinja2 Flask || fail
        python2 -m pip install numpy --upgrade || fail
    fi
    msg "Installation for the extra packages finishes."
fi

if [ "x${MODE}" = "xjupyter" ]
then
    bash /root/scripts/install-jlab version=${JLAB_VERSION} ex_tiers=${JLAB_EXTRA_TIERS} compat=${JLAB_COMPATIBLE} || fail
    msg "Installation for the Jupyter Lab finishes."
fi
