#!/bin/bash

# Make bashline configurations.
set -e
RESET='\033[0m'
COLOR='\033[1;32m'

function msg {
  echo -e "${COLOR}$(date): $1${RESET}"
}

function fail {
  msg "Error : $?"
  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 --slave /usr/bin/g++ g++ /usr/bin/g++-5  --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-5
  exit 1
}

function mcd {
  mkdir -p "$1" || fail
  cd "$1" || fail
}

# The script for installing newest ffmpeg
apt-get -y update -qq || fail && apt-get -y install \
  autoconf \
  automake \
  build-essential \
  cmake \
  libtool \
  git \
  pkg-config \
  wget \
  zlib1g-dev \
  build-essential \
  software-properties-common \
  libprotobuf-dev \
  protobuf-compiler \
  python-protobuf || fail

apt-get -y install gcc-5 gfortran-5 g++-5 || fail
apt-get -y install gcc-6 gfortran-6 g++-6 || fail

apt-get -y update || fail && apt-get -y upgrade || fail && apt-get -y dist-upgrade || fail && apt-get -y autoremove || fail && apt-get -y autoclean || fail

update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7 || fail
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 95 --slave /usr/bin/g++ g++ /usr/bin/g++-5 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-5 || fail
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-6 || fail

SOURCE_PATH="/apps/source/gcc"
BUILD_PATH="/apps/build/gcc"
BIN_PATH="/usr/local"
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/compat/lib:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/nvvm/lib64:/usr/local/lib64:/usr/lib:/usr/local/lib:/lib:/lib/x86_64-linux-gnu:/lib/i386-linux-gnu"
MKL_CBWR=AUTO
mkdir -p $SOURCE_PATH $BUILD_PATH $BIN_PATH/gcc-6 $BIN_PATH/gcc-9 || fail
mkdir -p $SOURCE_PATH/src/google/protobuf/ || fail
cp libprotobuf/* $SOURCE_PATH/src/google/protobuf/

# Install gcc-9
msg "Installing gcc-9."
cd $SOURCE_PATH || fail
wget http://ftp.gnu.org/gnu/gcc/gcc-9.2.0/gcc-9.2.0.tar.xz || fail
tar -xf gcc-9.2.0.tar.xz || fail && cd gcc-9.2.0 || fail
./contrib/download_prerequisites || fail
mkdir -p $BUILD_PATH/gcc-9.2.0 || fail && cd $BUILD_PATH/gcc-9.2.0 || fail
$SOURCE_PATH/gcc-9.2.0/configure                     \
    --prefix=$BIN_PATH                               \
    --program-suffix=-9                              \
    --enable-shared                                  \
    --enable-threads=posix                           \
    --enable-clocale=gnu                             \
    --disable-multilib                               \
    --with-system-zlib                               \
    --enable-languages=c,c++,fortran,go,objc,obj-c++ || fail
make -j32 || fail
make install || fail

update-alternatives --install /usr/bin/gcc gcc /usr/local/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/local/bin/g++-9 --slave /usr/bin/gfortran gfortran /usr/local/bin/gfortran-9 || fail
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 --slave /usr/bin/g++ g++ /usr/bin/g++-5  --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-5

# Install libprotobuf with gcc-9
msg "Installing libprotobuf with gcc-9."
SOURCE_PATH="/apps/source"
BUILD_PATH="/apps/build"
BIN_PATH="/usr/local"
# Build and install protobuf
cd $SOURCE_PATH || fail
git clone -b 'v3.10.1' --single-branch --depth 1 https://github.com/google/protobuf.git || fail
cd protobuf || fail
./autogen.sh || fail
cd $BUILD_PATH || fail
mkdir -p protobuf || fail && cd protobuf || fail
$SOURCE_PATH/protobuf/configure           \
    --prefix=$BIN_PATH || fail
make -j32 || fail
make -j32 install || fail
ldconfig || fail

echo "export LD_LIBRARY_PATH=$BIN_PATH/lib64:\$LD_LIBRARY_PATH" >> ~/.bashrc
echo "export PKG_CONFIG_LIBDIR=$BIN_PATH/lib64:\$PKG_CONFIG_LIBDIR" >> ~/.bashrc
export LD_LIBRARY_PATH=$BIN_PATH/lib64:$LD_LIBRARY_PATH
export PKG_CONFIG_LIBDIR=$BIN_PATH/lib64:$PKG_CONFIG_LIBDIR

msg "Installation finished. Now you could use \"update-alternatives --config gcc\" to control the version of gcc/g++."
